### ISSUE TITLE
Cannot change workspace in SoapUI 5.6.0

### ISSUE THREAD

**Issue by janher** [SmartBear/soapui#534] opened 2020-08-10 09:40 UTC
I experience the problem described in https://community.smartbear.com/t5/SoapUI-Open-Source/Cannot-change-workspace-in-SoapUI-5-6-0/m-p/204620#M30895 
After choosing a different workspace file, the old workspace stays loaded. The SoapUI log tab gives no new entries after I try to switch workspaces. The error log stays empty.
Any advise on further troubleshooting or solving this is appreciated.

For me this is a showstopper that prevents me from updating to SoapUI 5.6.0

**Comment by sudheeranguluri** [comment] 2020-09-02 16:45
any updates on this? Facing the same issue on 5.6.0

**Comment by 0xAnasEzz** [comment] 2020-10-25 12:51
Same issue on **5.6.0**
OS: **Windows 10 x64**

**Comment by widc** [comment] 2020-11-23 13:10
Workaround:
1. Copy default-soapui-workspace.xml to some other workspace file and edit manually (e.g. leave just one project, it doesn't matter much, you can add/remove the projects later in the tool).
2. Run the tool with the path to the workspace file in the command line option, e.g.
`"C:\Program Files\SmartBear\SoapUI-5.6.0\bin\SoapUI-5.6.0.exe" -w "c:\Users\widc\experimenty-soapui-workspace.xml"`

The above solution was found by looking at the source _SoapUI.java_ around the line 970.

**Comment by deniszitu** [comment] 2021-10-06 07:25
Workaround:

Uncheck this 
Preferences -> UI Settings -> [Show Startup Page](https://www.soapui.org/docs/preferences-and-settings/#:~:text=Show%20Startup%20Page)
and restart SoapUI

**Comment by 0xAnasEzz** [comment] 2021-10-14 12:09
> 
> 
> Workaround:
> 
> Uncheck this Preferences -> UI Settings -> [Show Startup Page](https://www.soapui.org/docs/preferences-and-settings/#:~:text=Show%20Startup%20Page) and restart SoapUI

Can't figure out how this worked, but it just does the job.

**Comment by ReadyAPIAgent** [comment] 2022-01-13 13:16
fixed by 5.7.0

**Closed as completed by ReadyAPIAgent** 2022-01-13 13:16 UTC

**Comment by Hrozhek** [comment] 2022-02-01 07:52
In 5.7.0 workspaces cannot be switched too.
Update: there is a choice when switch worspace offering to save previous one. If I choose "yes" nothing happens, and old workspace is left. In I choose "no" then empty workspace is open instead of existing workspace.

**Comment by 0xAnasEzz** [comment] 2022-02-02 12:27
> In 5.7.0 workspaces cannot be switched too. Update: there is a choice when switch worspace offering to save previous one. If I choose "yes" nothing happens, and old workspace is left. In I choose "no" then empty workspace is open instead of existing workspace.

I can't reproduce your described scenario on 5.7.0
